<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240304083200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE absence (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, createur_id INT NOT NULL, booking_id INT NOT NULL, category_id INT NOT NULL, document_id INT DEFAULT NULL, date_absence DATETIME NOT NULL, duree INT NOT NULL, all_day TINYINT(1) NOT NULL, INDEX IDX_765AE0C9A76ED395 (user_id), INDEX IDX_765AE0C973A201E5 (createur_id), INDEX IDX_765AE0C93301C60 (booking_id), INDEX IDX_765AE0C912469DE2 (category_id), INDEX IDX_765AE0C9C33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE absence_category (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE batiment (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bloc_competence (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, description VARCHAR(255) NOT NULL, ordre INT NOT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_711471E9727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bloc_competence_valide (id INT AUTO_INCREMENT NOT NULL, promotion_id INT NOT NULL, competence_id INT NOT NULL, prof_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_2BC2BE7A139DF194 (promotion_id), INDEX IDX_2BC2BE7A15761DAB (competence_id), INDEX IDX_2BC2BE7AABC1F7FE (prof_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking (id INT AUTO_INCREMENT NOT NULL, prof_id INT NOT NULL, promotion_id INT NOT NULL, matiere_id INT NOT NULL, salle_id INT NOT NULL, title VARCHAR(255) NOT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, description VARCHAR(255) DEFAULT NULL, all_day TINYINT(1) NOT NULL, textcolor VARCHAR(7) DEFAULT NULL, INDEX IDX_E00CEDDEABC1F7FE (prof_id), INDEX IDX_E00CEDDE139DF194 (promotion_id), INDEX IDX_E00CEDDEF46CD258 (matiere_id), INDEX IDX_E00CEDDEDC304035 (salle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, structure_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) NOT NULL, INDEX IDX_4C62E6382534008B (structure_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrat (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours (id INT AUTO_INCREMENT NOT NULL, createur_id INT NOT NULL, matiere_id INT NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_FDCA8C9C73A201E5 (createur_id), INDEX IDX_FDCA8C9CF46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_session_formation (cours_id INT NOT NULL, session_formation_id INT NOT NULL, INDEX IDX_4E474B467ECF78B0 (cours_id), INDEX IDX_4E474B469C9D95AF (session_formation_id), PRIMARY KEY(cours_id, session_formation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_formation (cours_id INT NOT NULL, formation_id INT NOT NULL, INDEX IDX_B8E51B787ECF78B0 (cours_id), INDEX IDX_B8E51B785200282E (formation_id), PRIMARY KEY(cours_id, formation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_bloc_competence (cours_id INT NOT NULL, bloc_competence_id INT NOT NULL, INDEX IDX_570A349D7ECF78B0 (cours_id), INDEX IDX_570A349DEC8CB2A4 (bloc_competence_id), PRIMARY KEY(cours_id, bloc_competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_distance (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, cours_id INT NOT NULL, cours_seq_id INT DEFAULT NULL, open_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', valid_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DB06345CA76ED395 (user_id), INDEX IDX_DB06345C7ECF78B0 (cours_id), INDEX IDX_DB06345C48A5EC42 (cours_seq_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_seq (id INT AUTO_INCREMENT NOT NULL, cours_id INT NOT NULL, createur_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', nom VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, ordre INT NOT NULL, INDEX IDX_36B5C5347ECF78B0 (cours_id), INDEX IDX_36B5C53473A201E5 (createur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cours_seq_document (cours_seq_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_175C932C48A5EC42 (cours_seq_id), INDEX IDX_175C932CC33F7837 (document_id), PRIMARY KEY(cours_seq_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir (id INT AUTO_INCREMENT NOT NULL, createur_id INT NOT NULL, promotion_id INT NOT NULL, matiere_id INT NOT NULL, type_id INT NOT NULL, intitule_technique_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_devoir DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', coefficient INT NOT NULL, date_d DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_f DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', active TINYINT(1) NOT NULL, INDEX IDX_749EA77173A201E5 (createur_id), INDEX IDX_749EA771139DF194 (promotion_id), INDEX IDX_749EA771F46CD258 (matiere_id), INDEX IDX_749EA771C54C8C93 (type_id), INDEX IDX_749EA771D70485A4 (intitule_technique_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_bloc_competence (devoir_id INT NOT NULL, bloc_competence_id INT NOT NULL, INDEX IDX_7495E5AEC583534E (devoir_id), INDEX IDX_7495E5AEEC8CB2A4 (bloc_competence_id), PRIMARY KEY(devoir_id, bloc_competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_document (devoir_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_9EBDB4A3C583534E (devoir_id), INDEX IDX_9EBDB4A3C33F7837 (document_id), PRIMARY KEY(devoir_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_note (id INT AUTO_INCREMENT NOT NULL, devoir_id INT NOT NULL, user_id INT NOT NULL, note DOUBLE PRECISION NOT NULL, remarque VARCHAR(255) DEFAULT NULL, absent TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3A484BC4C583534E (devoir_id), INDEX IDX_3A484BC4A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_qcm (id INT AUTO_INCREMENT NOT NULL, devoir_id INT NOT NULL, question LONGTEXT NOT NULL, rep_a LONGTEXT NOT NULL, rep_b LONGTEXT NOT NULL, rep_c LONGTEXT DEFAULT NULL, rep_d LONGTEXT DEFAULT NULL, vrai VARCHAR(255) NOT NULL, point DOUBLE PRECISION NOT NULL, reponse LONGTEXT DEFAULT NULL, INDEX IDX_2DD479A3C583534E (devoir_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_qcm_rendu (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, devoir_qcm_id INT NOT NULL, question_qcm_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', reponse VARCHAR(255) NOT NULL, INDEX IDX_52AE78A6A76ED395 (user_id), INDEX IDX_52AE78A6C23CF256 (devoir_qcm_id), INDEX IDX_52AE78A6F83F6EAE (question_qcm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_rendu (id INT AUTO_INCREMENT NOT NULL, devoir_id INT NOT NULL, eleve_id INT NOT NULL, promotion_id INT NOT NULL, rendu_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', commentaire LONGTEXT DEFAULT NULL, INDEX IDX_AC59A9DCC583534E (devoir_id), INDEX IDX_AC59A9DCA6CC7B2 (eleve_id), INDEX IDX_AC59A9DC139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_rendu_document (devoir_rendu_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_690BFC6D8FA0E738 (devoir_rendu_id), INDEX IDX_690BFC6DC33F7837 (document_id), PRIMARY KEY(devoir_rendu_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devoir_t (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, document_category_id INT NOT NULL, create_date DATETIME NOT NULL, update_date DATETIME DEFAULT NULL, nom VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, content LONGBLOB NOT NULL, archive_date DATETIME DEFAULT NULL, INDEX IDX_D8698A7690EFAA88 (document_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_category (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, global TINYINT(1) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domaine (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enquete (id INT AUTO_INCREMENT NOT NULL, categorie_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', code VARCHAR(255) NOT NULL, INDEX IDX_D6D86B29BCF5E72D (categorie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enquete_qcm (id INT AUTO_INCREMENT NOT NULL, enquete_id INT NOT NULL, question LONGTEXT NOT NULL, rep_a VARCHAR(255) NOT NULL, rep_b VARCHAR(255) NOT NULL, rep_c VARCHAR(255) NOT NULL, rep_d VARCHAR(255) NOT NULL, vrai INT NOT NULL, point INT NOT NULL, INDEX IDX_25231B8D5FDC5003 (enquete_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enquete_reponse (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, enquete_id INT NOT NULL, question_id INT DEFAULT NULL, reponse INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BCAE4A63A76ED395 (user_id), INDEX IDX_BCAE4A635FDC5003 (enquete_id), INDEX IDX_BCAE4A631E27F6BF (question_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, type_entreprise_id INT NOT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, cp VARCHAR(6) NOT NULL, ville VARCHAR(255) NOT NULL, contact_civilite VARCHAR(255) DEFAULT NULL, contact_nom VARCHAR(255) DEFAULT NULL, contact_mail VARCHAR(255) DEFAULT NULL, contact_tel VARCHAR(255) DEFAULT NULL, contact_poste VARCHAR(255) DEFAULT NULL, remarque VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', taille VARCHAR(255) NOT NULL, code_naf VARCHAR(10) NOT NULL, INDEX IDX_D19FA60A76ED395 (user_id), INDEX IDX_D19FA60D44318DF (type_entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise_dossier (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, user_id INT NOT NULL, etat_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_end DATETIME NOT NULL, INDEX IDX_85AC5384A4AEAFEA (entreprise_id), INDEX IDX_85AC5384A76ED395 (user_id), INDEX IDX_85AC5384D5E86FF (etat_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise_note (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, dossier_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type_note VARCHAR(255) NOT NULL, INDEX IDX_4428ED33A76ED395 (user_id), INDEX IDX_4428ED33611C0C56 (dossier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise_type (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etat (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE formation (id INT AUTO_INCREMENT NOT NULL, niveau_entree_id INT DEFAULT NULL, niveau_sortie_id INT DEFAULT NULL, type_formation_id INT DEFAULT NULL, domaine_id INT DEFAULT NULL, rythme_id INT DEFAULT NULL, referentiel_id INT DEFAULT NULL, description LONGTEXT NOT NULL, objectif LONGTEXT NOT NULL, debouche LONGTEXT NOT NULL, nom VARCHAR(255) NOT NULL, duree INT NOT NULL, has_stage TINYINT(1) NOT NULL, prix_formation DOUBLE PRECISION NOT NULL, prix_annexe DOUBLE PRECISION DEFAULT NULL, code_rncp VARCHAR(255) DEFAULT NULL, lien_rncp VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_404021BFFDAA3DE6 (niveau_entree_id), INDEX IDX_404021BF9EA33DA5 (niveau_sortie_id), INDEX IDX_404021BFD543922B (type_formation_id), INDEX IDX_404021BF4272FC9F (domaine_id), INDEX IDX_404021BF8399A4A6 (rythme_id), UNIQUE INDEX UNIQ_404021BF805DB139 (referentiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE formation_bloc_competence (formation_id INT NOT NULL, bloc_competence_id INT NOT NULL, INDEX IDX_E2CADA045200282E (formation_id), INDEX IDX_E2CADA04EC8CB2A4 (bloc_competence_id), PRIMARY KEY(formation_id, bloc_competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_droit (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, remarque LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_fonctionnalite (id INT AUTO_INCREMENT NOT NULL, groupe_fonctionnalite_category_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, remarque LONGTEXT DEFAULT NULL, INDEX IDX_E8C2F4D14F5CBF1E (groupe_fonctionnalite_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_fonctionnalite_groupe_droit (groupe_fonctionnalite_id INT NOT NULL, groupe_droit_id INT NOT NULL, INDEX IDX_2A81CD14EFB01DFA (groupe_fonctionnalite_id), INDEX IDX_2A81CD14CB0B3800 (groupe_droit_id), PRIMARY KEY(groupe_fonctionnalite_id, groupe_droit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_fonctionnalite_category (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intitule_technique (id INT AUTO_INCREMENT NOT NULL, formation_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_54E7A46A5200282E (formation_id), INDEX IDX_54E7A46AF46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE liaison (id INT AUTO_INCREMENT NOT NULL, prof_id INT NOT NULL, promotion_id INT NOT NULL, createur_id INT NOT NULL, code VARCHAR(30) NOT NULL, date_dat DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_fat DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', nb_heures DOUBLE PRECISION DEFAULT NULL, tarif DOUBLE PRECISION DEFAULT NULL, INDEX IDX_225AC37ABC1F7FE (prof_id), INDEX IDX_225AC37139DF194 (promotion_id), INDEX IDX_225AC3773A201E5 (createur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE liaison_bloc_competence (liaison_id INT NOT NULL, bloc_competence_id INT NOT NULL, INDEX IDX_AA02EFACED31185 (liaison_id), INDEX IDX_AA02EFACEC8CB2A4 (bloc_competence_id), PRIMARY KEY(liaison_id, bloc_competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE localisation (id INT AUTO_INCREMENT NOT NULL, batiment_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, cp VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, etage INT NOT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_BFD3CE8FD6F6891B (batiment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, log_category_id INT NOT NULL, titre VARCHAR(255) NOT NULL, contenu LONGTEXT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_8F3F68C5A76ED395 (user_id), INDEX IDX_8F3F68C54EFFE14A (log_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log_category (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE matiere (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, couleur VARCHAR(255) NOT NULL, couleur_texte VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE niveau (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_synthese (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE provenance (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rythme (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salle (id INT AUTO_INCREMENT NOT NULL, localisation_id INT DEFAULT NULL, salle_category_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, capacite INT NOT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_4E977E5CC68BE09C (localisation_id), INDEX IDX_4E977E5CECF90A61 (salle_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salle_category (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE session_formation (id INT AUTO_INCREMENT NOT NULL, formation_id INT DEFAULT NULL, professeur_referent_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, duree_stage INT DEFAULT NULL, satisfaction DOUBLE PRECISION DEFAULT NULL, abandon DOUBLE PRECISION DEFAULT NULL, reussite DOUBLE PRECISION DEFAULT NULL, is_archive TINYINT(1) NOT NULL, nom_promotion VARCHAR(255) DEFAULT NULL, annee VARCHAR(20) NOT NULL, INDEX IDX_3A264B55200282E (formation_id), INDEX IDX_3A264B53D2DFE8E (professeur_referent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE session_formation_matiere (session_formation_id INT NOT NULL, matiere_id INT NOT NULL, INDEX IDX_16C7CC379C9D95AF (session_formation_id), INDEX IDX_16C7CC37F46CD258 (matiere_id), PRIMARY KEY(session_formation_id, matiere_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE structure (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suivi_category (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suivi_session (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, description LONGTEXT NOT NULL, remarque VARCHAR(500) DEFAULT NULL, UNIQUE INDEX UNIQ_558321713301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suivi_session_bloc_competence (suivi_session_id INT NOT NULL, bloc_competence_id INT NOT NULL, INDEX IDX_A7481FA0CB5C007B (suivi_session_id), INDEX IDX_A7481FA0EC8CB2A4 (bloc_competence_id), PRIMARY KEY(suivi_session_id, bloc_competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suivi_session_document (suivi_session_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_C1101363CB5C007B (suivi_session_id), INDEX IDX_C1101363C33F7837 (document_id), PRIMARY KEY(suivi_session_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suivi_user (id INT AUTO_INCREMENT NOT NULL, redacteur_id INT DEFAULT NULL, concerne_id INT DEFAULT NULL, category_id INT NOT NULL, date_suivi DATE NOT NULL, contenu LONGTEXT NOT NULL, is_visible TINYINT(1) NOT NULL, is_changement_statut TINYINT(1) NOT NULL, INDEX IDX_3DB3812B764D0490 (redacteur_id), INDEX IDX_3DB3812B6406FEF1 (concerne_id), INDEX IDX_3DB3812B12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket (id INT AUTO_INCREMENT NOT NULL, createur_id INT NOT NULL, category_id INT NOT NULL, technicien_id INT DEFAULT NULL, description VARCHAR(1000) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', opened_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', closed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', reponse LONGTEXT DEFAULT NULL, INDEX IDX_97A0ADA373A201E5 (createur_id), INDEX IDX_97A0ADA312469DE2 (category_id), INDEX IDX_97A0ADA313457256 (technicien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket_category (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_formation (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, tuteur_id INT DEFAULT NULL, contrat_id INT DEFAULT NULL, provenance_id INT NOT NULL, structure_id INT DEFAULT NULL, niveau_id INT DEFAULT NULL, dossier_id INT DEFAULT NULL, cv_id INT DEFAULT NULL, rythme_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, is_verified TINYINT(1) NOT NULL, date_naissance DATETIME DEFAULT NULL, tel VARCHAR(15) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, cp VARCHAR(10) DEFAULT NULL, ville VARCHAR(40) DEFAULT NULL, num_pole_emploi VARCHAR(20) DEFAULT NULL, num_secu VARCHAR(20) DEFAULT NULL, montant_cpf INT DEFAULT NULL, dernier_diplome VARCHAR(100) DEFAULT NULL, dernier_emploi VARCHAR(100) DEFAULT NULL, is_handicap TINYINT(1) NOT NULL, rq_handicap VARCHAR(255) DEFAULT NULL, rq_generale VARCHAR(255) DEFAULT NULL, attestation_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_droit_image TINYINT(1) NOT NULL, attestation_droit_image_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', rq_user VARCHAR(255) DEFAULT NULL, reglement_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', entretien_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', test_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', resultat_test DOUBLE PRECISION DEFAULT NULL, decision VARCHAR(255) DEFAULT NULL, decision_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D64986EC68D8 (tuteur_id), INDEX IDX_8D93D6491823061F (contrat_id), INDEX IDX_8D93D649C24AFBDB (provenance_id), INDEX IDX_8D93D6492534008B (structure_id), INDEX IDX_8D93D649B3E9C81 (niveau_id), INDEX IDX_8D93D649611C0C56 (dossier_id), INDEX IDX_8D93D649CFE419E2 (cv_id), INDEX IDX_8D93D6498399A4A6 (rythme_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_groupe_droit (user_id INT NOT NULL, groupe_droit_id INT NOT NULL, INDEX IDX_1E1B1503A76ED395 (user_id), INDEX IDX_1E1B1503CB0B3800 (groupe_droit_id), PRIMARY KEY(user_id, groupe_droit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_matiere (user_id INT NOT NULL, matiere_id INT NOT NULL, INDEX IDX_C8194940A76ED395 (user_id), INDEX IDX_C8194940F46CD258 (matiere_id), PRIMARY KEY(user_id, matiere_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_session_formation (user_id INT NOT NULL, session_formation_id INT NOT NULL, INDEX IDX_FBBDDF9EA76ED395 (user_id), INDEX IDX_FBBDDF9E9C9D95AF (session_formation_id), PRIMARY KEY(user_id, session_formation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE valid_doc (id INT AUTO_INCREMENT NOT NULL, document_id INT NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_9CC09CD8C33F7837 (document_id), INDEX IDX_9CC09CD8A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C973A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C93301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C912469DE2 FOREIGN KEY (category_id) REFERENCES absence_category (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE bloc_competence ADD CONSTRAINT FK_711471E9727ACA70 FOREIGN KEY (parent_id) REFERENCES bloc_competence (id)');
        $this->addSql('ALTER TABLE bloc_competence_valide ADD CONSTRAINT FK_2BC2BE7A139DF194 FOREIGN KEY (promotion_id) REFERENCES session_formation (id)');
        $this->addSql('ALTER TABLE bloc_competence_valide ADD CONSTRAINT FK_2BC2BE7A15761DAB FOREIGN KEY (competence_id) REFERENCES bloc_competence (id)');
        $this->addSql('ALTER TABLE bloc_competence_valide ADD CONSTRAINT FK_2BC2BE7AABC1F7FE FOREIGN KEY (prof_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEABC1F7FE FOREIGN KEY (prof_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE139DF194 FOREIGN KEY (promotion_id) REFERENCES session_formation (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEDC304035 FOREIGN KEY (salle_id) REFERENCES salle (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6382534008B FOREIGN KEY (structure_id) REFERENCES structure (id)');
        $this->addSql('ALTER TABLE cours ADD CONSTRAINT FK_FDCA8C9C73A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cours ADD CONSTRAINT FK_FDCA8C9CF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE cours_session_formation ADD CONSTRAINT FK_4E474B467ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_session_formation ADD CONSTRAINT FK_4E474B469C9D95AF FOREIGN KEY (session_formation_id) REFERENCES session_formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_formation ADD CONSTRAINT FK_B8E51B787ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_formation ADD CONSTRAINT FK_B8E51B785200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_bloc_competence ADD CONSTRAINT FK_570A349D7ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_bloc_competence ADD CONSTRAINT FK_570A349DEC8CB2A4 FOREIGN KEY (bloc_competence_id) REFERENCES bloc_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_distance ADD CONSTRAINT FK_DB06345CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cours_distance ADD CONSTRAINT FK_DB06345C7ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id)');
        $this->addSql('ALTER TABLE cours_distance ADD CONSTRAINT FK_DB06345C48A5EC42 FOREIGN KEY (cours_seq_id) REFERENCES cours_seq (id)');
        $this->addSql('ALTER TABLE cours_seq ADD CONSTRAINT FK_36B5C5347ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id)');
        $this->addSql('ALTER TABLE cours_seq ADD CONSTRAINT FK_36B5C53473A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cours_seq_document ADD CONSTRAINT FK_175C932C48A5EC42 FOREIGN KEY (cours_seq_id) REFERENCES cours_seq (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours_seq_document ADD CONSTRAINT FK_175C932CC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA77173A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA771139DF194 FOREIGN KEY (promotion_id) REFERENCES session_formation (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA771F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA771C54C8C93 FOREIGN KEY (type_id) REFERENCES devoir_t (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA771D70485A4 FOREIGN KEY (intitule_technique_id) REFERENCES intitule_technique (id)');
        $this->addSql('ALTER TABLE devoir_bloc_competence ADD CONSTRAINT FK_7495E5AEC583534E FOREIGN KEY (devoir_id) REFERENCES devoir (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir_bloc_competence ADD CONSTRAINT FK_7495E5AEEC8CB2A4 FOREIGN KEY (bloc_competence_id) REFERENCES bloc_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir_document ADD CONSTRAINT FK_9EBDB4A3C583534E FOREIGN KEY (devoir_id) REFERENCES devoir (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir_document ADD CONSTRAINT FK_9EBDB4A3C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir_note ADD CONSTRAINT FK_3A484BC4C583534E FOREIGN KEY (devoir_id) REFERENCES devoir (id)');
        $this->addSql('ALTER TABLE devoir_note ADD CONSTRAINT FK_3A484BC4A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE devoir_qcm ADD CONSTRAINT FK_2DD479A3C583534E FOREIGN KEY (devoir_id) REFERENCES devoir (id)');
        $this->addSql('ALTER TABLE devoir_qcm_rendu ADD CONSTRAINT FK_52AE78A6A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE devoir_qcm_rendu ADD CONSTRAINT FK_52AE78A6C23CF256 FOREIGN KEY (devoir_qcm_id) REFERENCES devoir (id)');
        $this->addSql('ALTER TABLE devoir_qcm_rendu ADD CONSTRAINT FK_52AE78A6F83F6EAE FOREIGN KEY (question_qcm_id) REFERENCES devoir_qcm (id)');
        $this->addSql('ALTER TABLE devoir_rendu ADD CONSTRAINT FK_AC59A9DCC583534E FOREIGN KEY (devoir_id) REFERENCES devoir (id)');
        $this->addSql('ALTER TABLE devoir_rendu ADD CONSTRAINT FK_AC59A9DCA6CC7B2 FOREIGN KEY (eleve_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE devoir_rendu ADD CONSTRAINT FK_AC59A9DC139DF194 FOREIGN KEY (promotion_id) REFERENCES session_formation (id)');
        $this->addSql('ALTER TABLE devoir_rendu_document ADD CONSTRAINT FK_690BFC6D8FA0E738 FOREIGN KEY (devoir_rendu_id) REFERENCES devoir_rendu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE devoir_rendu_document ADD CONSTRAINT FK_690BFC6DC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7690EFAA88 FOREIGN KEY (document_category_id) REFERENCES document_category (id)');
        $this->addSql('ALTER TABLE enquete ADD CONSTRAINT FK_D6D86B29BCF5E72D FOREIGN KEY (categorie_id) REFERENCES devoir_t (id)');
        $this->addSql('ALTER TABLE enquete_qcm ADD CONSTRAINT FK_25231B8D5FDC5003 FOREIGN KEY (enquete_id) REFERENCES enquete (id)');
        $this->addSql('ALTER TABLE enquete_reponse ADD CONSTRAINT FK_BCAE4A63A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE enquete_reponse ADD CONSTRAINT FK_BCAE4A635FDC5003 FOREIGN KEY (enquete_id) REFERENCES enquete (id)');
        $this->addSql('ALTER TABLE enquete_reponse ADD CONSTRAINT FK_BCAE4A631E27F6BF FOREIGN KEY (question_id) REFERENCES enquete_qcm (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60D44318DF FOREIGN KEY (type_entreprise_id) REFERENCES entreprise_type (id)');
        $this->addSql('ALTER TABLE entreprise_dossier ADD CONSTRAINT FK_85AC5384A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE entreprise_dossier ADD CONSTRAINT FK_85AC5384A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE entreprise_dossier ADD CONSTRAINT FK_85AC5384D5E86FF FOREIGN KEY (etat_id) REFERENCES etat (id)');
        $this->addSql('ALTER TABLE entreprise_note ADD CONSTRAINT FK_4428ED33A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE entreprise_note ADD CONSTRAINT FK_4428ED33611C0C56 FOREIGN KEY (dossier_id) REFERENCES entreprise_dossier (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BFFDAA3DE6 FOREIGN KEY (niveau_entree_id) REFERENCES niveau (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF9EA33DA5 FOREIGN KEY (niveau_sortie_id) REFERENCES niveau (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BFD543922B FOREIGN KEY (type_formation_id) REFERENCES type_formation (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF4272FC9F FOREIGN KEY (domaine_id) REFERENCES domaine (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF8399A4A6 FOREIGN KEY (rythme_id) REFERENCES rythme (id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF805DB139 FOREIGN KEY (referentiel_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE formation_bloc_competence ADD CONSTRAINT FK_E2CADA045200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE formation_bloc_competence ADD CONSTRAINT FK_E2CADA04EC8CB2A4 FOREIGN KEY (bloc_competence_id) REFERENCES bloc_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_fonctionnalite ADD CONSTRAINT FK_E8C2F4D14F5CBF1E FOREIGN KEY (groupe_fonctionnalite_category_id) REFERENCES groupe_fonctionnalite_category (id)');
        $this->addSql('ALTER TABLE groupe_fonctionnalite_groupe_droit ADD CONSTRAINT FK_2A81CD14EFB01DFA FOREIGN KEY (groupe_fonctionnalite_id) REFERENCES groupe_fonctionnalite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_fonctionnalite_groupe_droit ADD CONSTRAINT FK_2A81CD14CB0B3800 FOREIGN KEY (groupe_droit_id) REFERENCES groupe_droit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE intitule_technique ADD CONSTRAINT FK_54E7A46A5200282E FOREIGN KEY (formation_id) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE intitule_technique ADD CONSTRAINT FK_54E7A46AF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE liaison ADD CONSTRAINT FK_225AC37ABC1F7FE FOREIGN KEY (prof_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE liaison ADD CONSTRAINT FK_225AC37139DF194 FOREIGN KEY (promotion_id) REFERENCES session_formation (id)');
        $this->addSql('ALTER TABLE liaison ADD CONSTRAINT FK_225AC3773A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE liaison_bloc_competence ADD CONSTRAINT FK_AA02EFACED31185 FOREIGN KEY (liaison_id) REFERENCES liaison (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE liaison_bloc_competence ADD CONSTRAINT FK_AA02EFACEC8CB2A4 FOREIGN KEY (bloc_competence_id) REFERENCES bloc_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FD6F6891B FOREIGN KEY (batiment_id) REFERENCES batiment (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C54EFFE14A FOREIGN KEY (log_category_id) REFERENCES log_category (id)');
        $this->addSql('ALTER TABLE salle ADD CONSTRAINT FK_4E977E5CC68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id)');
        $this->addSql('ALTER TABLE salle ADD CONSTRAINT FK_4E977E5CECF90A61 FOREIGN KEY (salle_category_id) REFERENCES salle_category (id)');
        $this->addSql('ALTER TABLE session_formation ADD CONSTRAINT FK_3A264B55200282E FOREIGN KEY (formation_id) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE session_formation ADD CONSTRAINT FK_3A264B53D2DFE8E FOREIGN KEY (professeur_referent_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE session_formation_matiere ADD CONSTRAINT FK_16C7CC379C9D95AF FOREIGN KEY (session_formation_id) REFERENCES session_formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_formation_matiere ADD CONSTRAINT FK_16C7CC37F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE suivi_session ADD CONSTRAINT FK_558321713301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE suivi_session_bloc_competence ADD CONSTRAINT FK_A7481FA0CB5C007B FOREIGN KEY (suivi_session_id) REFERENCES suivi_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE suivi_session_bloc_competence ADD CONSTRAINT FK_A7481FA0EC8CB2A4 FOREIGN KEY (bloc_competence_id) REFERENCES bloc_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE suivi_session_document ADD CONSTRAINT FK_C1101363CB5C007B FOREIGN KEY (suivi_session_id) REFERENCES suivi_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE suivi_session_document ADD CONSTRAINT FK_C1101363C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE suivi_user ADD CONSTRAINT FK_3DB3812B764D0490 FOREIGN KEY (redacteur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE suivi_user ADD CONSTRAINT FK_3DB3812B6406FEF1 FOREIGN KEY (concerne_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE suivi_user ADD CONSTRAINT FK_3DB3812B12469DE2 FOREIGN KEY (category_id) REFERENCES suivi_category (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA373A201E5 FOREIGN KEY (createur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA312469DE2 FOREIGN KEY (category_id) REFERENCES ticket_category (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA313457256 FOREIGN KEY (technicien_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D64986EC68D8 FOREIGN KEY (tuteur_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D6491823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649C24AFBDB FOREIGN KEY (provenance_id) REFERENCES provenance (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D6492534008B FOREIGN KEY (structure_id) REFERENCES structure (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649611C0C56 FOREIGN KEY (dossier_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649CFE419E2 FOREIGN KEY (cv_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D6498399A4A6 FOREIGN KEY (rythme_id) REFERENCES rythme (id)');
        $this->addSql('ALTER TABLE user_groupe_droit ADD CONSTRAINT FK_1E1B1503A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_groupe_droit ADD CONSTRAINT FK_1E1B1503CB0B3800 FOREIGN KEY (groupe_droit_id) REFERENCES groupe_droit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_matiere ADD CONSTRAINT FK_C8194940A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_matiere ADD CONSTRAINT FK_C8194940F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_session_formation ADD CONSTRAINT FK_FBBDDF9EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_session_formation ADD CONSTRAINT FK_FBBDDF9E9C9D95AF FOREIGN KEY (session_formation_id) REFERENCES session_formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE valid_doc ADD CONSTRAINT FK_9CC09CD8C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE valid_doc ADD CONSTRAINT FK_9CC09CD8A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9A76ED395');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C973A201E5');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C93301C60');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C912469DE2');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9C33F7837');
        $this->addSql('ALTER TABLE bloc_competence DROP FOREIGN KEY FK_711471E9727ACA70');
        $this->addSql('ALTER TABLE bloc_competence_valide DROP FOREIGN KEY FK_2BC2BE7A139DF194');
        $this->addSql('ALTER TABLE bloc_competence_valide DROP FOREIGN KEY FK_2BC2BE7A15761DAB');
        $this->addSql('ALTER TABLE bloc_competence_valide DROP FOREIGN KEY FK_2BC2BE7AABC1F7FE');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEABC1F7FE');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE139DF194');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEF46CD258');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEDC304035');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E6382534008B');
        $this->addSql('ALTER TABLE cours DROP FOREIGN KEY FK_FDCA8C9C73A201E5');
        $this->addSql('ALTER TABLE cours DROP FOREIGN KEY FK_FDCA8C9CF46CD258');
        $this->addSql('ALTER TABLE cours_session_formation DROP FOREIGN KEY FK_4E474B467ECF78B0');
        $this->addSql('ALTER TABLE cours_session_formation DROP FOREIGN KEY FK_4E474B469C9D95AF');
        $this->addSql('ALTER TABLE cours_formation DROP FOREIGN KEY FK_B8E51B787ECF78B0');
        $this->addSql('ALTER TABLE cours_formation DROP FOREIGN KEY FK_B8E51B785200282E');
        $this->addSql('ALTER TABLE cours_bloc_competence DROP FOREIGN KEY FK_570A349D7ECF78B0');
        $this->addSql('ALTER TABLE cours_bloc_competence DROP FOREIGN KEY FK_570A349DEC8CB2A4');
        $this->addSql('ALTER TABLE cours_distance DROP FOREIGN KEY FK_DB06345CA76ED395');
        $this->addSql('ALTER TABLE cours_distance DROP FOREIGN KEY FK_DB06345C7ECF78B0');
        $this->addSql('ALTER TABLE cours_distance DROP FOREIGN KEY FK_DB06345C48A5EC42');
        $this->addSql('ALTER TABLE cours_seq DROP FOREIGN KEY FK_36B5C5347ECF78B0');
        $this->addSql('ALTER TABLE cours_seq DROP FOREIGN KEY FK_36B5C53473A201E5');
        $this->addSql('ALTER TABLE cours_seq_document DROP FOREIGN KEY FK_175C932C48A5EC42');
        $this->addSql('ALTER TABLE cours_seq_document DROP FOREIGN KEY FK_175C932CC33F7837');
        $this->addSql('ALTER TABLE devoir DROP FOREIGN KEY FK_749EA77173A201E5');
        $this->addSql('ALTER TABLE devoir DROP FOREIGN KEY FK_749EA771139DF194');
        $this->addSql('ALTER TABLE devoir DROP FOREIGN KEY FK_749EA771F46CD258');
        $this->addSql('ALTER TABLE devoir DROP FOREIGN KEY FK_749EA771C54C8C93');
        $this->addSql('ALTER TABLE devoir DROP FOREIGN KEY FK_749EA771D70485A4');
        $this->addSql('ALTER TABLE devoir_bloc_competence DROP FOREIGN KEY FK_7495E5AEC583534E');
        $this->addSql('ALTER TABLE devoir_bloc_competence DROP FOREIGN KEY FK_7495E5AEEC8CB2A4');
        $this->addSql('ALTER TABLE devoir_document DROP FOREIGN KEY FK_9EBDB4A3C583534E');
        $this->addSql('ALTER TABLE devoir_document DROP FOREIGN KEY FK_9EBDB4A3C33F7837');
        $this->addSql('ALTER TABLE devoir_note DROP FOREIGN KEY FK_3A484BC4C583534E');
        $this->addSql('ALTER TABLE devoir_note DROP FOREIGN KEY FK_3A484BC4A76ED395');
        $this->addSql('ALTER TABLE devoir_qcm DROP FOREIGN KEY FK_2DD479A3C583534E');
        $this->addSql('ALTER TABLE devoir_qcm_rendu DROP FOREIGN KEY FK_52AE78A6A76ED395');
        $this->addSql('ALTER TABLE devoir_qcm_rendu DROP FOREIGN KEY FK_52AE78A6C23CF256');
        $this->addSql('ALTER TABLE devoir_qcm_rendu DROP FOREIGN KEY FK_52AE78A6F83F6EAE');
        $this->addSql('ALTER TABLE devoir_rendu DROP FOREIGN KEY FK_AC59A9DCC583534E');
        $this->addSql('ALTER TABLE devoir_rendu DROP FOREIGN KEY FK_AC59A9DCA6CC7B2');
        $this->addSql('ALTER TABLE devoir_rendu DROP FOREIGN KEY FK_AC59A9DC139DF194');
        $this->addSql('ALTER TABLE devoir_rendu_document DROP FOREIGN KEY FK_690BFC6D8FA0E738');
        $this->addSql('ALTER TABLE devoir_rendu_document DROP FOREIGN KEY FK_690BFC6DC33F7837');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7690EFAA88');
        $this->addSql('ALTER TABLE enquete DROP FOREIGN KEY FK_D6D86B29BCF5E72D');
        $this->addSql('ALTER TABLE enquete_qcm DROP FOREIGN KEY FK_25231B8D5FDC5003');
        $this->addSql('ALTER TABLE enquete_reponse DROP FOREIGN KEY FK_BCAE4A63A76ED395');
        $this->addSql('ALTER TABLE enquete_reponse DROP FOREIGN KEY FK_BCAE4A635FDC5003');
        $this->addSql('ALTER TABLE enquete_reponse DROP FOREIGN KEY FK_BCAE4A631E27F6BF');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60A76ED395');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60D44318DF');
        $this->addSql('ALTER TABLE entreprise_dossier DROP FOREIGN KEY FK_85AC5384A4AEAFEA');
        $this->addSql('ALTER TABLE entreprise_dossier DROP FOREIGN KEY FK_85AC5384A76ED395');
        $this->addSql('ALTER TABLE entreprise_dossier DROP FOREIGN KEY FK_85AC5384D5E86FF');
        $this->addSql('ALTER TABLE entreprise_note DROP FOREIGN KEY FK_4428ED33A76ED395');
        $this->addSql('ALTER TABLE entreprise_note DROP FOREIGN KEY FK_4428ED33611C0C56');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BFFDAA3DE6');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF9EA33DA5');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BFD543922B');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF4272FC9F');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF8399A4A6');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF805DB139');
        $this->addSql('ALTER TABLE formation_bloc_competence DROP FOREIGN KEY FK_E2CADA045200282E');
        $this->addSql('ALTER TABLE formation_bloc_competence DROP FOREIGN KEY FK_E2CADA04EC8CB2A4');
        $this->addSql('ALTER TABLE groupe_fonctionnalite DROP FOREIGN KEY FK_E8C2F4D14F5CBF1E');
        $this->addSql('ALTER TABLE groupe_fonctionnalite_groupe_droit DROP FOREIGN KEY FK_2A81CD14EFB01DFA');
        $this->addSql('ALTER TABLE groupe_fonctionnalite_groupe_droit DROP FOREIGN KEY FK_2A81CD14CB0B3800');
        $this->addSql('ALTER TABLE intitule_technique DROP FOREIGN KEY FK_54E7A46A5200282E');
        $this->addSql('ALTER TABLE intitule_technique DROP FOREIGN KEY FK_54E7A46AF46CD258');
        $this->addSql('ALTER TABLE liaison DROP FOREIGN KEY FK_225AC37ABC1F7FE');
        $this->addSql('ALTER TABLE liaison DROP FOREIGN KEY FK_225AC37139DF194');
        $this->addSql('ALTER TABLE liaison DROP FOREIGN KEY FK_225AC3773A201E5');
        $this->addSql('ALTER TABLE liaison_bloc_competence DROP FOREIGN KEY FK_AA02EFACED31185');
        $this->addSql('ALTER TABLE liaison_bloc_competence DROP FOREIGN KEY FK_AA02EFACEC8CB2A4');
        $this->addSql('ALTER TABLE localisation DROP FOREIGN KEY FK_BFD3CE8FD6F6891B');
        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C5A76ED395');
        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C54EFFE14A');
        $this->addSql('ALTER TABLE salle DROP FOREIGN KEY FK_4E977E5CC68BE09C');
        $this->addSql('ALTER TABLE salle DROP FOREIGN KEY FK_4E977E5CECF90A61');
        $this->addSql('ALTER TABLE session_formation DROP FOREIGN KEY FK_3A264B55200282E');
        $this->addSql('ALTER TABLE session_formation DROP FOREIGN KEY FK_3A264B53D2DFE8E');
        $this->addSql('ALTER TABLE session_formation_matiere DROP FOREIGN KEY FK_16C7CC379C9D95AF');
        $this->addSql('ALTER TABLE session_formation_matiere DROP FOREIGN KEY FK_16C7CC37F46CD258');
        $this->addSql('ALTER TABLE suivi_session DROP FOREIGN KEY FK_558321713301C60');
        $this->addSql('ALTER TABLE suivi_session_bloc_competence DROP FOREIGN KEY FK_A7481FA0CB5C007B');
        $this->addSql('ALTER TABLE suivi_session_bloc_competence DROP FOREIGN KEY FK_A7481FA0EC8CB2A4');
        $this->addSql('ALTER TABLE suivi_session_document DROP FOREIGN KEY FK_C1101363CB5C007B');
        $this->addSql('ALTER TABLE suivi_session_document DROP FOREIGN KEY FK_C1101363C33F7837');
        $this->addSql('ALTER TABLE suivi_user DROP FOREIGN KEY FK_3DB3812B764D0490');
        $this->addSql('ALTER TABLE suivi_user DROP FOREIGN KEY FK_3DB3812B6406FEF1');
        $this->addSql('ALTER TABLE suivi_user DROP FOREIGN KEY FK_3DB3812B12469DE2');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA373A201E5');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA312469DE2');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA313457256');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D64986EC68D8');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D6491823061F');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649C24AFBDB');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D6492534008B');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649B3E9C81');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649611C0C56');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649CFE419E2');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D6498399A4A6');
        $this->addSql('ALTER TABLE user_groupe_droit DROP FOREIGN KEY FK_1E1B1503A76ED395');
        $this->addSql('ALTER TABLE user_groupe_droit DROP FOREIGN KEY FK_1E1B1503CB0B3800');
        $this->addSql('ALTER TABLE user_matiere DROP FOREIGN KEY FK_C8194940A76ED395');
        $this->addSql('ALTER TABLE user_matiere DROP FOREIGN KEY FK_C8194940F46CD258');
        $this->addSql('ALTER TABLE user_session_formation DROP FOREIGN KEY FK_FBBDDF9EA76ED395');
        $this->addSql('ALTER TABLE user_session_formation DROP FOREIGN KEY FK_FBBDDF9E9C9D95AF');
        $this->addSql('ALTER TABLE valid_doc DROP FOREIGN KEY FK_9CC09CD8C33F7837');
        $this->addSql('ALTER TABLE valid_doc DROP FOREIGN KEY FK_9CC09CD8A76ED395');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE absence_category');
        $this->addSql('DROP TABLE batiment');
        $this->addSql('DROP TABLE bloc_competence');
        $this->addSql('DROP TABLE bloc_competence_valide');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contrat');
        $this->addSql('DROP TABLE cours');
        $this->addSql('DROP TABLE cours_session_formation');
        $this->addSql('DROP TABLE cours_formation');
        $this->addSql('DROP TABLE cours_bloc_competence');
        $this->addSql('DROP TABLE cours_distance');
        $this->addSql('DROP TABLE cours_seq');
        $this->addSql('DROP TABLE cours_seq_document');
        $this->addSql('DROP TABLE devoir');
        $this->addSql('DROP TABLE devoir_bloc_competence');
        $this->addSql('DROP TABLE devoir_document');
        $this->addSql('DROP TABLE devoir_note');
        $this->addSql('DROP TABLE devoir_qcm');
        $this->addSql('DROP TABLE devoir_qcm_rendu');
        $this->addSql('DROP TABLE devoir_rendu');
        $this->addSql('DROP TABLE devoir_rendu_document');
        $this->addSql('DROP TABLE devoir_t');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_category');
        $this->addSql('DROP TABLE domaine');
        $this->addSql('DROP TABLE enquete');
        $this->addSql('DROP TABLE enquete_qcm');
        $this->addSql('DROP TABLE enquete_reponse');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE entreprise_dossier');
        $this->addSql('DROP TABLE entreprise_note');
        $this->addSql('DROP TABLE entreprise_type');
        $this->addSql('DROP TABLE etat');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE formation_bloc_competence');
        $this->addSql('DROP TABLE groupe_droit');
        $this->addSql('DROP TABLE groupe_fonctionnalite');
        $this->addSql('DROP TABLE groupe_fonctionnalite_groupe_droit');
        $this->addSql('DROP TABLE groupe_fonctionnalite_category');
        $this->addSql('DROP TABLE intitule_technique');
        $this->addSql('DROP TABLE liaison');
        $this->addSql('DROP TABLE liaison_bloc_competence');
        $this->addSql('DROP TABLE localisation');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE log_category');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE niveau');
        $this->addSql('DROP TABLE page_synthese');
        $this->addSql('DROP TABLE provenance');
        $this->addSql('DROP TABLE rythme');
        $this->addSql('DROP TABLE salle');
        $this->addSql('DROP TABLE salle_category');
        $this->addSql('DROP TABLE session_formation');
        $this->addSql('DROP TABLE session_formation_matiere');
        $this->addSql('DROP TABLE structure');
        $this->addSql('DROP TABLE suivi_category');
        $this->addSql('DROP TABLE suivi_session');
        $this->addSql('DROP TABLE suivi_session_bloc_competence');
        $this->addSql('DROP TABLE suivi_session_document');
        $this->addSql('DROP TABLE suivi_user');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_category');
        $this->addSql('DROP TABLE type_formation');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_groupe_droit');
        $this->addSql('DROP TABLE user_matiere');
        $this->addSql('DROP TABLE user_session_formation');
        $this->addSql('DROP TABLE valid_doc');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
